//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_toilet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Toilet
    {
        public int Id { get; set; }
        public string ToiletCode { get; set; }
        public bool IsActive { get; set; }
        public string Address { get; set; }
        public string Lat { get; set; }
        public string Lng { get; set; }
    }
}
